### ISSUE TITLE
Synaptics SMBus on Catalina Support

### ISSUE THREAD

**Issue by aofathy** [VoodooSMBus/VoodooSMBus#27]
Hello there,

I have a Lenovo V130-15IKB which apparently uses Synaptics SYNA2B42, I tried VoodooI2C to find out after two sleepless nights that my Synaptics is directly connected to the SMBus controller which made me come to this project. Trying with VoodooI2C there were no change at all even in Trackpad PrefPane, but once I used your amazing kext, there was a tiny change that the Trackpad PrefPane was finally enabled but to find out later that your kext doesn't support Synaptics yet as I understood.

So is there any hope for us? this is literally my last step for a usable hackintosh on a Laptop.

![Screen Shot 2020-04-08 at 11 45 05 AM](https://user-images.githubusercontent.com/2502019/78777409-c0cf7500-7999-11ea-8494-38ca785c6d88.png)

![Screen Shot 2020-04-08 at 11 45 15 AM](https://user-images.githubusercontent.com/2502019/78777413-c331cf00-7999-11ea-903e-283053e8d4a2.png)

**Comment by leo-labs** [comment]
Have you checkout https://github.com/Sniki/Lenovo-V330-15IKB ? Your touchpad might be connected to both the SMBus and the I2C

**Comment by aofathy** [comment]
Just tried and nope back to no trackpad PrefPane and this screenshot from IOReg.
![Screen Shot 2020-04-09 at 1 26 36 AM](https://user-images.githubusercontent.com/2502019/78842748-33277000-7a01-11ea-90c6-4a564659919e.png)

And I'm pretty sure it's SMBus only according to my lspci from Kali Linux
![Screen Shot 2020-04-09 at 1 23 39 AM](https://user-images.githubusercontent.com/2502019/78842679-f5c2e280-7a00-11ea-99fb-b66528ba6961.png)

**Comment by leo-labs** [comment]
Someone got VoodooI2C working with the exact same laptop https://gitter.im/alexandred/VoodooI2C/archives/2018/10/17?at=5bc66491c7bf7c366221cb93

And I am not an expert but isn't there an I2C controller in your `lspci` output?

**Comment by aofathy** [comment]
Yeah I found that too while searching but no success at all. It just shows me the IOName is XXXX0000 even with GPI0 pinning and everthing.. to find out later @gokula said to @alexandred it was directly connected to the SMBus which made me come here.

I'm not an expert too, but I thought it might help.

**Comment by leo-labs** [comment]
It is possible to add synaptics support to VoodooSMBus, right now only ELAN devices are supported. If you want to give it a try, I can help you.

**Comment by aofathy** [comment]
If this won't bother you, yes please!
I could help by any means you would want to.

**Comment by leo-labs** [comment]
Come join us at https://gitter.im/VoodooSMBus/dev, we are trying to implement the synaptics support

**Comment by 1Revenger1** [comment]
https://github.com/VoodooSMBus/VoodooRMI Here's the repo for the Synaptics stuff.
Touchpad does work, but buttons and trackpoiont don't.
I also put it into it's own repo a couple days ago which completely broke linking, lol. Once I get that fixed, we should get more progress.

**Comment by 1Revenger1** [comment]
There's an initial release now of VoodooRMI for synaptic pads.
