### ISSUE TITLE
Trackpad and trackpoint went wrong at sometimes

### ISSUE THREAD

**Issue by xiaotianxt** [VoodooSMBus/VoodooSMBus#38]
I'm using VoodooSMBus and VoodooPS2Controller, the trackpad is smooth in most situation, but it can be suddenly unusable with no sign, and will restore to normal in a few minutes(sometimes a few hours), it's really annoying and I'm confused why this happens....

**Comment by xiaotianxt** [comment]
Sorry for my poor English, and I'm new in hackintosh, so I'm open to any questions and advices😀

**Comment by leo-labs** [comment]
Is it possible that you press the `PrtSc` button on your keyboard? This will toggle the tochpad input completely

**Comment by xiaotianxt** [comment]
> Is it possible that you press the `PrtSc` button on your keyboard? This will toggle the tochpad input completely

No I didn't, but I fixed it now by copying other's EFI folders, thanks a lot anyway!
