### ISSUE TITLE
Plan for ELAN PS2 Driver?

### ISSUE THREAD

**Issue by Sher1ocks** [VoodooSMBus/VoodooSMBus#39]
hi first of all. thank you for your hard work.
i want to know ELAN PS2 Support.
many elan ps2 touch pad user use ApplePS2SmartTouchPad.kext.
this driver is discontinued.
can you support elan ps2?

**Comment by leo-labs** [comment]
We do not plan to support PS2 at any time. Most ELAN touchpads support a better transport protocol such as I2C or SMBus. You need to find out which protocol is supported by your touchpad: An easy to do that is to check how Linux or Windows are connecting to the touchpad. If you find that it is connected via SMBus, please follow the instructions in the README. If you find out it is connected via I2C, please use https://github.com/VoodooI2C/VoodooI2C
If there is really no support for I2C or SMBus, please use https://github.com/acidanthera/VoodooPS2

**Comment by BAndysc** [comment]
Hello @Sher1ocks! Good news, I have the same hardware as you and same problem as you. Therefore I have ported elan ps2 support from linux into voodoo ps2: https://github.com/BAndysc/VoodooPS2/releases/tag/elanps2.v1

It works very well for me, but it is hardware - you never know about other devices... If I get more feedback, it might be merged into official Voodoo PS2, therefore I will be glad if you could test and report if it works for your touchpad!

**Comment by Sher1ocks** [comment]
> Hello @Sher1ocks! Good news, I have the same hardware as you and same problem as you. Therefore I have ported elan ps2 support from linux into voodoo ps2: https://github.com/BAndysc/VoodooPS2/releases/tag/elanps2.v1
> 
> It works very well for me, but it is hardware - you never know about other devices... If I get more feedback, it might be merged into official Voodoo PS2, therefore I will be glad if you could test and report if it works for your touchpad!

good!!!! thank you for hard work. 
i wiil test it after finish work today.

**Comment by Sher1ocks** [comment]
> Hello @Sher1ocks! Good news, I have the same hardware as you and same problem as you. Therefore I have ported elan ps2 support from linux into voodoo ps2: https://github.com/BAndysc/VoodooPS2/releases/tag/elanps2.v1
> 
> It works very well for me, but it is hardware - you never know about other devices... If I get more feedback, it might be merged into official Voodoo PS2, therefore I will be glad if you could test and report if it works for your touchpad!

perfect!!! @BAndysc you save me!!!!
this build not include debug mode.
if you want, please debug kext. i will post log

**Comment by Sher1ocks** [comment]
> Hello @Sher1ocks! Good news, I have the same hardware as you and same problem as you. Therefore I have ported elan ps2 support from linux into voodoo ps2: https://github.com/BAndysc/VoodooPS2/releases/tag/elanps2.v1
> 
> It works very well for me, but it is hardware - you never know about other devices... If I get more feedback, it might be merged into official Voodoo PS2, therefore I will be glad if you could test and report if it works for your touchpad!

issue 1.
after wakeup, touchpad is not working.

**Comment by leo-labs** [comment]
Great that you have found a solution and that ELAN PS2 support is coming to VoodooSPS2. 

Please continue the discussion in the VoodooPS2 fork :)
